[project]
name = "simple-agent"
version = "0.1.0"
description = "Simple A2A agent"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "a2a-sdk[http-server]>=0.3.20",
    "litellm>=1.80.9",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.38.0",
]
